### ISSUE TITLE
Add a link to the events page

### ISSUE THREAD

**Issue by apoorva-mk** [acm-w-nitk/acm-w-nitk.github.io#55]
The events page is already present in the Html folder
In index.html add a link to it under the get involved section -> events (it should say click here for more).

**Comment by rakshathavasudev** [comment]
Can I complete this issue @apoorva-mk

**Comment by apoorva-mk** [comment]
> Can I complete this issue @apoorva-mk

Thank you @rakshathavasudev, please submit your PR :)
