### ISSUE TITLE
Make discover.html responsive

### ISSUE THREAD

**Issue by apoorva-mk** [acm-w-nitk/acm-w-nitk.github.io#58]
The file can be found at html -> discover.html

**Comment by efl7a** [comment]
What exactly do you mean by "responsive"? Do you mean the button leads to somewhere?

**Comment by apoorva-mk** [comment]
> What exactly do you mean by "responsive"? Do you mean the button leads to somewhere?

Hi, @efl7a you can refer this link for more about [responsive web design](https://www.w3schools.com/html/html_responsive.asp)

**Comment by hazeliao** [comment]
Hi, I have just finished creating a pull request to you girls. I hope this is what you are aiming for with responsive web design on this part of your project. 😸

**Comment by hazeliao** [comment]
> > Hi, I have just finished creating a pull request to you girls. I hope this is what you are aiming for with responsive web design on this part of your project. smile_cat @apoorva-mk
> 
> Hi, @hazeliao thank you for contributing. please also make sure you follow the contributing guidelines which would make it easier for us.

Hi I'm so sorry I didn't know I should read the contributing guide 😨 I will do that in the future!

**Comment by apoorva-mk** [comment]
> > > Hi, I have just finished creating a pull request to you girls. I hope this is what you are aiming for with responsive web design on this part of your project. smile_cat @apoorva-mk
> > 
> > 
> > Hi, @hazeliao thank you for contributing. please also make sure you follow the contributing guidelines which would make it easier for us.
> 
> Hi I'm so sorry I didn't know I should read the contributing guide fearful I will do that in the future!

Hi, @hazeliao that's alright, it just helps in keeping everything organized and smoothly functioning. :smile:
