### ISSUE TITLE
Add link to our github page

### ISSUE THREAD

**Issue by apoorva-mk** [acm-w-nitk/acm-w-nitk.github.io#72]
## Problem

We would like a link from our website to this repo. It should be done like so [(refer the top right of this website)](http://guides.railsgirls.com/guide)

Please find the corner [here](http://tholman.com/github-corners/)

**Comment by suleimanbashiru** [comment]
Will take this up and also do you want the link in the navbar or where

**Comment by AdrianJVillalobos** [comment]
Hello, I would like to take this at @NovaHelm

**Comment by apoorva-mk** [comment]
> Will take this up and also do you want the link in the navbar or where

@suleimanbashiru we wanted it exactly like in the link given (with some animation as well), and yes it will be in the top right of the website.

**Comment by apoorva-mk** [comment]
> Hello, I would like to take this at @NovaHelm

@AdrianJVillalobos we will assign it to you if the issue is not worked upon, thank you for showing interest in our community.
