### ISSUE TITLE
FAQ section

### ISSUE THREAD

**Issue by apoorva-mk** [acm-w-nitk/acm-w-nitk.github.io#75]
## Problem

We would like to have an faq section in the home page itself.

## Solution

Create a separate faq section in the homepage, please reuse code and styling so that it looks uniform.

## Alternatives

Have a separate page, for FAQs

**Comment by tushar-nitave** [comment]
I am on it.

**Comment by tushar-nitave** [comment]
Are there any list of faqs that needs to be added?

**Comment by apoorva-mk** [comment]
> Are there any list of faqs that needs to be added?

For now you can just use some dummy text or any generic question, the content isn't prepared yet.

**Comment by adarshbalu** [comment]
Is it done? Can I work on this?

**Comment by pradipta007** [comment]
Can I work on this?

**Comment by pradipta007** [comment]
@emred2700 @apoorva-mk  Does referencing means i have to edit the referenced issue (#86 ) that emred2700 gave?I am new on this platform

**Comment by apoorva-mk** [comment]
> @emred2700 @apoorva-mk Does referencing means i have to edit the referenced issue (#86 ) that emred2700 gave?I am new on this platform

This issue has already been claimes, it would be great if you can work on another one or raise a new issue. Referencing the issue means adding the issue number in the commit header.
